# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'terminal-table', '~> 1.8'gem 'colorize', '~> 0.8.1'gem 'rubocop', '~> 0.92.0'gem 'json', '~> 2.3', '>= 2.3.1'gem 'tty-prompt', '~> 0.22.0'gem 'rspec', '~> 3.9'